### ISSUE TITLE
Styleguide Component: buttons

### ISSUE THREAD

**Issue by zivl** [onap-sdc/sdc-ui#10]

**Comment by michalweinsh** [comment]
the design for the Default and Outline buttons is available on adobe cloud.
will provide the rest of the buttons later.

**Comment by onap-sdc** [comment]
@arieldkenan will start to work on it

**Comment by michalweinsh** [comment]
@ArielDKenan i updated the file. please make sure you're implementing Open Sans font.

**Comment by zivl** [comment]
@michalweinsh - the font stuff is related to issue #42 - please update there if it is the final decision and we'll apply
