### ISSUE TITLE
348462/Form elements

### ISSUE THREAD

**Issue by fridmaster** [onap-sdc/sdc-ui#144]
– styles + radio buttons

**Comment by lizronen** [comment]
[Domain_2_Ui Github_BTN.zip](https://github.com/onap-sdc/sdc-ui/files/1457063/Domain_2_Ui.Github_BTN.zip)
[Uploading Domain_2_Ui Github_INPUTS.zip…]()

**Comment by bardit** [comment]
[Domain_2_Ui Github_INPUTS.zip](https://github.com/onap-sdc/sdc-ui/files/1457059/Domain_2_Ui.Github_INPUTS.zip)
[Domain_2_Ui Github_BTN.zip](https://github.com/onap-sdc/sdc-ui/files/1457060/Domain_2_Ui.Github_BTN.zip)
