### ISSUE TITLE
Exclude angular files from Jest

### ISSUE THREAD

**Issue by ibaraness** [onap-sdc/sdc-ui#154]
Hi, 
I've found a problem with current Jest configuration, it tries to test angular test files and other unrelated files, like 'webpack.test.js' file. Those files return a false fail test.  I've tried to exclude it locally. I've added the following paths to  'testPathIgnorePatterns' array in the Jest config file and it solved the problem:

'<rootDir>/webpack/webpack.test.js',
'<rootDir>/src/angular/',
'<rootDir>/lib/angular/' 

But I think it's better to restrict Jest to specific react test folders. To your consideration.
@einavk , @ArielDKenan @islavi

**Comment by einavk** [comment]
@ArielDKenan - can you please have a look at this?
