### ISSUE TITLE
Angular/Tiles

### ISSUE THREAD

**Issue by fridmaster** [onap-sdc/sdc-ui#236]
After one of update stories of Tiles was broken.

**Comment by ArielDKenan** [comment]
Hey Leib,

There are two mistakes that are being made right now:

1. The 'content icon' is being inserted into the 'content info' section. The 'content' area is meant to contain the icon and the info, so the icon should be directly under the .sdc-content class/component, along with the info, not inside the info.

2. Inside the content-info section, the title classes are being used in the wrong order. '.supertitle' should be used for an info-line above the title, '.subtitle' for one below the title, and '.title' for the title.

**Comment by fridmaster** [comment]
@ArielDKenan When I made rollback of css - I also changed template to right order. I don't know how - something or someone broke it.

**Comment by ArielDKenan** [comment]
Yes I saw it was changed and changed back again

**Comment by ArielDKenan** [comment]
It was fixed in #247
