### ISSUE TITLE
What is the font of this framework?

### ISSUE THREAD

**Issue by zivl** [onap-sdc/sdc-ui#42]
I would suggest any web-safe font from this list:
http://www.cssfontstack.com/

The advantages of 'web-safe' fonts:
* it doesn't affect the load performance (i.e. the time the user has to wait until he sees something on screen and ready to take an action) - as UI/UX people, it should matter to you
* it mitigates the visual differentiation between browsers (Mozilla, Chrome...)

**Comment by michalweinsh** [comment]
I'm hoping we can use nicer fonts than the web-safe ones, so we're checking if Open Sans font is acceptable by all sides. it's a good font with 10 styles, good spacing and it’s free.
Aleck font is still being checked if it can be used in an open-source framework.
i'm waiting to their response. in the meantime i'm in favor of Open Sans.

**Comment by zivl** [comment]
attaching link: https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans

**Comment by michalweinsh** [comment]
@lizronen - above is my suggestion for the font. please update me if Roboto is also suitable for this framework.

**Comment by einavk** [comment]
Open Sans was chosen. added in issue #47

**Comment by michalweinsh** [comment]
@lizronen - FYI - we implemented open sans

**Comment by zivl** [comment]
@lizronen, @islavi - do we have a *legal* clearance to put this font in our repository? can you please approve it here?

**Comment by islavi** [comment]
@zivl  I sent request to AT&T for approval of this GitHub project.
But regarding the font, I talked with Michael Lando, we can use this font (MIT) license in our project. So I do not see any problem why not to add it here.
We need to add it to our project, and not external link to CDN.

**Comment by zivl** [comment]
@islavi - so please upload it

**Comment by zivl** [comment]
resolved in PR #76
