### ISSUE TITLE
Style Guide Checkboxes: Behavior

### ISSUE THREAD

**Issue by ArielDKenan** [onap-sdc/sdc-ui#50]
The first checkbox example (Checked) cannot be unchecked, but the second one (Unchecked) can be checked. The desired behavior should be for the user to be able to uncheck and recheck both boxes.

**Comment by einavk** [comment]
Yeah, I see that. Small defect. Same one on radio as well. Will fix and submit ASAP.

**Comment by ArielDKenan** [comment]
Actually the "radio" component seems to behave correctly. It is just one radio box (Checked) so it shouldn't be able to be unselected, or associated with the example below it (Unchecked). The RadioGroups component shows an example where you can see the behavior of switching selection of radio buttons in a group.

**Comment by einavk** [comment]
Ariel, the radio had the same issue, it was just not noticeable there. However, having noticed it, I had a discussion with @nomrik and @zivl , and we decided that the best approach would be not to use state for the different form input, but rather expect it to be handled later on by the using app, via onChange handler. It will not work on storybook, but the tests reflect the changes and are working.
